# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "ea99bf002074f933c82c6ae0ac0a83a9"
name = "Saku Link In Bio"
handle = "saku-link-in-bio"
application_url = "https://sfy-link-in-bio-app.saku.so"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = """
read_files,
write_files,
read_online_store_navigation,
write_online_store_navigation,
read_products,
read_themes,
read_metaobjects,
write_metaobjects,
read_metaobject_definitions,
write_metaobject_definitions,
unauthenticated_read_checkouts,
unauthenticated_write_checkouts,
unauthenticated_read_metaobjects,
unauthenticated_read_product_listings
"""

[auth]
redirect_urls = [
  "https://sfy-link-in-bio-app.saku.so/auth/callback",
  "https://sfy-link-in-bio-app.saku.so/auth/shopify/callback",
  "https://sfy-link-in-bio-app.saku.so/api/auth/callback",
]

[app_proxy]
url = "https://sfy-link-in-bio-app.saku.so/a/saku"
subpath = "saku"
prefix = "a"

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
topics = ["app/uninstalled"]
uri = "/api/v1/webhook/shopify/app/uninstalled"

[[webhooks.subscriptions]]
topics = ["app/scopes_update"]
uri = "/api/v1/webhook/shopify/app/scopes_update"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request"]
uri = "/api/v1/webhook/shopify/customers/data_request"

[[webhooks.subscriptions]]
compliance_topics = ["customers/redact"]
uri = "/api/v1/webhook/shopify/customers/redact"

[[webhooks.subscriptions]]
compliance_topics = ["shop/redact"]
uri = "/api/v1/webhook/shopify/shop/redact"

[pos]
embedded = false

# https://shopify.dev/docs/apps/build/custom-data
[metaobjects.app.site_cache]
name = "Site Cache"
access.admin = "merchant_read"

[metaobjects.app.site_cache.fields.site_id]
name = "Site ID"
type = "single_line_text_field"
required = true

[metaobjects.app.site_cache.fields.content]
name = "Content"
type = "json"
required = true

[metaobjects.app.site_cache.fields.expires_at]
name = "Expires At"
type = "date_time"
required = true

[metaobjects.app.page]
name = "Saku page"
description = "A page created and managed by Saku"
display_name_field = "name"
access.admin = "merchant_read"
access.storefront = "public_read"
capabilities.publishable = true

[metaobjects.app.page.fields.name]
name = "Name"
type = "single_line_text_field"
required = true

[metaobjects.app.page.fields.document]
name = "Document"
type = "json"
required = true

[metaobjects.app.page.fields.products]
name = "Products"
type = "list.product_reference"
required = true

[metaobjects.app.page.fields.product_variants]
name = "Product variants"
type = "list.variant_reference"
required = true

[metaobjects.app.page.fields.files]
name = "Files"
type = "list.file_reference"
required = true
